# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1289, 891)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(270, 430, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(780, 430, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(470, 430, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(980, 430, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 80, 131, 51))
        self.label.setMinimumSize(QtCore.QSize(131, 0))
        self.label.setMaximumSize(QtCore.QSize(131, 61))
        self.label.setObjectName("label")
        self.PlainText = QtWidgets.QTextBrowser(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(230, 180, 361, 91))
        self.PlainText.setObjectName("PlainText")
        self.CipherText = QtWidgets.QTextBrowser(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(230, 290, 361, 91))
        self.CipherText.setObjectName("CipherText")
        self.Signature = QtWidgets.QTextBrowser(self.centralwidget)
        self.Signature.setGeometry(QtCore.QRect(760, 290, 361, 91))
        self.Signature.setObjectName("Signature")
        self.Information = QtWidgets.QTextBrowser(self.centralwidget)
        self.Information.setGeometry(QtCore.QRect(760, 160, 361, 91))
        self.Information.setObjectName("Information")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 190, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 310, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(666, 170, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 300, 47, 13))
        self.label_5.setObjectName("label_5")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(740, 90, 75, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1289, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encript"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decript"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "PlainText"))
        self.label_3.setText(_translate("MainWindow", "CipherText"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
